version: '3.8'

services:
  unisize-front:
    image: ghcr.io/uni-size/unisize-front:latest
    container_name: unisize-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # 환경 변수 파일이 필요한 경우 주석 해제
    # env_file:
    #   - .env.production
